parserOptions:
  ecmaVersion: 2017
  sourceType: module
env:
  browser: true
  es6: true
  node: true
globals:
  atom: true
rules:
  # Possible Errors
  for-direction: error
  getter-return: error
  no-await-in-loop: error
  no-compare-neg-zero: error
  no-cond-assign: error
  no-console: off
  no-control-regex: error
  no-debugger: off
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty:
    - error
    - allowEmptyCatch: true
  no-empty-character-class: error
  no-ex-assign: off
  no-extra-boolean-cast: error
  no-extra-parens: error
  no-extra-semi: error
  no-func-assign: error
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-obj-calls: error
  no-prototype-builtins: error
  no-regex-spaces: error
  no-sparse-arrays: error
  no-template-curly-in-string: error
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  use-isnan: error
  valid-jsdoc: error
  valid-typeof: error

  # Best Practices
  accessor-pairs: error
  array-callback-return: error
  block-scoped-var: error
  class-methods-use-this: error
  complexity: off
  consistent-return: off
  curly: error
  default-case: error
  dot-location: error
  dot-notation: error
  eqeqeq: error
  no-caller: error
  no-case-declarations: error
  no-div-regex: off
  no-else-return: error
  no-empty-function: error
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-fallthrough: error
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-coersion: off
  no-implicit-globals: off
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: off
  no-lone-blocks: off
  no-loop-func: error
  no-magic-numbers: off
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal: off
  no-octal-escape: off
  no-param-reassign: off
  no-proto: error
  no-redeclare: error
  no-restricted-properties: off
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-assign: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: off
  no-unused-expressions: error
  no-unused-labels: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-useless-return: error
  no-void: error
  no-warning-comments: off
  no-with: error
  prefer-promise-reject-errors: error
  radix:
    - error
    - as-needed
  require-await: error
  vars-on-top: off
  wrap-iife:
    - error
    - inside
  yoda: error

  # Strict Mode
  strict: error

  # Variables
  init-declarations: off
  no-catch-shadow: off
  no-delete-var: error
  no-label-var: error
  no-restricted-globals: off
  no-shadow:
    - error
    - allow:
      - err
      - e
  no-shadow-restricted-names: off
  no-undef: error
  no-undef-init: error
  no-undefined: error
  no-unused-vars: error
  no-use-before-define:
    - error
    - functions: false

  # Node.js and CommonJS
  callback-return: error
  global-require: off
  handle-callback-err: error
  no-buffer-constructor: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-process-env: off
  no-process-exit: off
  no-restricted-modules: off
  no-sync: off

  # Stylistic Issues
  array-bracket-newline: off
  array-bracket-spacing: error
  array-element-newline: off
  block-spacing: error
  brace-style: error
  camelcase:
    - error
    - properties: never
  capitalized-comments: off
  comma-dangle:
    - error
    - always-multiline
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  consistent-this: error
  eol-last: error
  func-call-spacing: error
  func-name-matching: off
  func-names: error
  func-style:
    - error
    - declaration
  function-paren-newline:
    - error
    - never
  id-blacklist: off
  id-length: off
  id-match: off
  indent:
    - error
    - tab
  implicit-arrow-linebreak: error
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  line-comment-position: off
  linebreak-style: error
  lines-around-comments: off
  max-depth: off
  max-len: off
  max-lines: off
  max-nested-callbacks: off
  max-params: off
  max-statements: off
  max-statements-per-line: error
  multiline-ternary: off
  new-cap: error
  new-parens: error
  newline-per-chained-call: off
  no-array-constructor: error
  no-bitwise: off
  no-continue: off
  no-inline-comments: off
  no-lonely-if: error
  no-mixed-operators: off
  no-mixed-spaces-and-tabs: error
  no-multi-assign: off
  no-multiple-empty-lines: error
  no-negated-condition: error
  no-nested-ternary: off
  no-new-object: error
  no-plusplus: off
  no-restricted-syntax: off
  no-tabs: off
  no-ternary: off
  no-trailing-spaces: error
  no-underscore-dangle: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  object-curly-newline:
    - error
    - ObjectExpression:
        minProperties: 1
      ObjectPattern: never
  object-curly-spacing: error
  object-property-newline: error
  one-var:
    - error
    - never
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks:
    - error
    - never
  padding-line-between-statements: off
  quote-props:
    - error
    - as-needed
  quotes: error
  require-jsdoc: off
  semi:
    - error
    - never
  semi-spacing: error
  semi-style:
    - error
    - first
  sort-keys: off
  sort-vars: off
  space-before-blocks: off
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  switch-colon-spacing: error
  template-tag-spacing: error
  unicode-bom: error
  wrap-regex: off

  # ECMAScript 6
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  constructor-super: error
  generator-star-spacing: error
  no-class-assign: error
  no-confusing-arrow: off
  no-const-assign: error
  no-dupe-class-members: error
  no-duplicate-imports: error
  no-new-symbol: error
  no-restricted-imports: off
  no-this-before-super: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring:
    - error
    - array: false
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  require-yield: error
  rest-spread-spacing: error
  sort-imports: error
  symbol-description: error
  template-curly-spacing: error
  yield-star-spacing: error
